# Generated by Django 4.0.2 on 2022-02-11 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Search_App', '0002_search_history_ip_alter_search_history_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_search', to=settings.AUTH_USER_MODEL),
        ),
    ]
