# Generated by Django 4.0.2 on 2022-02-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search_App', '0003_alter_search_history_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search_history',
            options={'ordering': ['-time']},
        ),
    ]
