# Generated by Django 4.0.2 on 2022-02-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search_App', '0004_alter_search_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search_history',
            options={},
        ),
    ]
